version: '3'
services:
  nest-backend:
    restart : unless-stopped	
    build:
      context: ./nnn-backend-nest/.
      dockerfile: "Dockerfile"
    links:
      - postgresdb
      - mongodb
    volumes:
      - ./nnn-backend-nest:/app
    networks:
      - backnet
    environment:
      PORT: ${PORT}
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb/${POSTGRES_DB}
      MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb/${MONGO_DB}?directConnection=true&serverSelectionTimeoutMS=2000&authSource=${MONGO_DB}
      RUST_SERVICE_URL: http://127.0.0.1:${RUST_PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgresdb
      - mongodb
      - rust-backend

  rust-backend:
    restart : unless-stopped	
    build:
      context: ./nnn-backend-rust/.
      dockerfile: "Dockerfile"
    links:
      - postgresdb
      - redisdb
      - mongodb
    volumes:
      - ./nnn-backend-rust:/app
    networks:
      - backnet
    ports:
      - 127.0.0.1:${RUST_PORT}:${RUST_PORT}
    environment:
      PG_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb/${POSTGRES_DB}
      REDIS_DATABASE_URI: redis://redisdb
      ADDRESS: 127.0.0.1:${RUST_PORT}
      FRONT_ORIGIN: http://127.0.0.1:${PORT}
    depends_on:
      - postgresdb
      - redisdb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo:/data
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backnet

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backnet
  
  redisdb:
    image: redis:latest
    volumes:
      - redis:/data
    networks:
      - backnet

volumes:
  mongo: {}
  redis: 
    driver: local
  postgres: {}

networks:
  backnet: